### ISSUE TITLE
Tethering broken

### ISSUE THREAD

**Issue by cdglitch** [SharkBoy69-CS/Lineage_OTA#1]
USB and WiFi tethering are broken. USB tethering enables but is not usable. Logcat complains about a lack of ipv4 address.

WiFi tethering fails to enable at all.

Testing with other SIMs shows that operators which are ipv4 only allows these to work. Ipv6 and dual stack operators cause tethering to be unusable.

`Routes: [ 0.0.0.0/0 -> 0.0.0.0 v4-rmnet_data1 mtu 0 ]} ]]}
07-12 15:14:28.055  3121  3343 I Tethering: Found upstream interface(s): [v4-rmnet_data1,rmnet_data1]
07-12 15:14:28.057  3121  3343 I Tethering: [wlan1] restart tethering: 0
07-12 15:14:28.157  3121  3343 I Tethering: [wlan1] Untethered (unrequested) and restarting wlan1
07-12 15:14:28.158  1678  2130 I WifiService: startTetheredHotspot uid=1073
07-12 15:14:28.174 14945 19958 I MagicTether: [AutoDisconnectIntentOperation] Canceling task. [CONTEXT service_id=276 ]
07-12 15:14:28.236  3121  3343 E Tethering: [wlan1] ERROR Failed to remove 1 IPv6 routes from local table.
07-12 15:14:28.238  3121  3343 E Tethering: [wlan1] ERROR failed to remove /2a00:23ee:2048:9570::b7/64: android.os.ServiceSpecificException: InterfaceController error: Cannot assign requested address (code 99)
07-12 15:14:28.238  3121  3343 E Tethering: [wlan1] ERROR Failed to remove local dns IP /2a00:23ee:2048:9570::b7
07-12 15:14:28.940  3121  3343 E Tethering: [wlan1] ERROR No available ipv4 address
07-12 15:14:28.970  3121  3343 E Tethering: [wlan1] ERROR Failed to untether interface: android.os.ServiceSpecificException: No such file or directory (code 2)
07-12 15:14:28.970  3121  3343 E Tethering: [wlan1] ERROR No available ipv4 address
07-12 15:14:28.977   587   587 I hwservicemanager: getTransport: Cannot find entry android.hardware.tetheroffload.config@1.0::IOffloadConfig/default in either framework or device VINTF manifest.
07-12 15:14:28.978  3121  3343 E Tethering: ERROR getIOffloadConfig error java.util.NoSuchElementException
07-12 15:14:28.978  3121  3343 E Tethering: [OffloadHardwareInterface] ERROR Could not find IOffloadConfig service
07-12 15:14:28.978  3121  3343 I Tethering: [OffloadController] tethering offload config not supported
07-12 15:14:28.978  3121  3343 I Tethering: [BpfCoordinator] BPF is not using
07-12 15:14:29.076 14945 19958 I MagicTether: [AutoDisconnectIntentOperation] Canceling task. [CONTEXT service_id=276 ]`

Version: 20-20230628-UNOFFICIAL-lavender

**Comment by 0xsharkboy** [comment]
I'll investigate it. Thanks for the report !

**Comment by 0xsharkboy** [comment]
Hey, usb tethering should be fine now. Can you test it on the last build please ?

**Comment by cdglitch** [comment]
Just tested the latest build. USB tethering is still a nogo on my device with the following in logcat

```
07-18 10:46:25.732  1609  1869 D UsbDeviceManager: push notification:USB tethering turned on
07-18 10:46:27.560  1609  1869 D UsbDeviceManager: push notification:USB tethering turned on
07-18 10:47:08.337  3496  3725 I Tethering: USB bcast connected:true configured:false rndis:false ncm:false
07-18 10:47:08.338  3496  3725 I Tethering: removing IpServer for: rndis0
07-18 10:47:08.480  3496  3725 I Tethering: USB bcast connected:true configured:true rndis:false ncm:false
07-18 10:47:09.076  3630  3630 I TetheringManager: startTethering caller:com.android.settings
07-18 10:47:09.524  1609  1869 D UsbDeviceManager: push notification:USB tethering turned on
07-18 10:47:09.528  3496  3725 I Tethering: USB bcast connected:true configured:false rndis:true ncm:false
07-18 10:47:09.739  3496  3725 I Tethering: USB bcast connected:true configured:true rndis:true ncm:false
07-18 10:47:09.744  3496  3725 I Tethering: adding IpServer for: rndis0
07-18 10:47:09.749  3496  3725 E Tethering: [rndis0] ERROR No available ipv4 address
07-18 10:47:09.753  3496  3725 E Tethering: [rndis0] ERROR Failed to untether interface: android.os.ServiceSpecificException: No such file or directory (code 2)
07-18 10:47:09.753  3496  3725 E Tethering: [rndis0] ERROR No available ipv4 address
07-18 10:47:09.766  3496  3725 I Tethering: [OffloadController] tethering offload disabled
07-18 10:47:09.768  3496  3725 I Tethering: [BpfCoordinator] BPF is not using
```

Slightly different output for wifi tethering though

```
07-18 10:48:33.843  3153  3246 I TetheringManager: startTethering caller:com.android.systemui
07-18 10:48:33.844  1609  3900 I WifiService: startTetheredHotspot uid=1073
07-18 10:48:34.592  3496  3725 E Tethering: [wlan1] ERROR No available ipv4 address
07-18 10:48:34.597  3496  3725 E Tethering: [wlan1] ERROR Failed to untether interface: android.os.ServiceSpecificException: No such file or directory (code 2)
07-18 10:48:34.597  3496  3725 E Tethering: [wlan1] ERROR No available ipv4 address
07-18 10:48:34.619  3496  3725 I Tethering: [OffloadController] tethering offload disabled
07-18 10:48:34.619  3496  3725 I Tethering: [BpfCoordinator] BPF is not using
07-18 10:48:34.679  3895 10870 I MagicTether: [AutoDisconnectIntentOperation] Canceling task. [CONTEXT service_id=276 ]
```
