### ISSUE TITLE
Missing changelog for 21.0 20241019/1729331289

### ISSUE THREAD

**Issue by m3thm4th** [SharkBoy69-CS/Lineage_OTA#10]
The [changelog](https://github.com/0xsharkboy/Lineage_OTA/blob/lineage-21.0/changelog.txt) for the [latest release](https://github.com/0xsharkboy/Lineage_OTA/releases/tag/lavender_lineage-21.0_1729331289) is missing

**Comment by 0xsharkboy** [comment]
Fixed it, thanks for the report
