### ISSUE TITLE
Crashed OTA application

### ISSUE THREAD

**Issue by JaGNUar** [SharkBoy69-CS/Lineage_OTA#2]
OTA application crashed when i want update system

**Comment by 0xsharkboy** [comment]
> OTA application crashed when i want update system

The Updater app ?

**Comment by JaGNUar** [comment]
> > OTA application crashed when i want update system
> 
> The Updater app ?

yes

**Comment by 0xsharkboy** [comment]
Build date ?

**Comment by JaGNUar** [comment]
Latest release 

https://github.com/SharkBoy69-CS/Lineage_OTA/assets/126384891/a09816d1-f7a8-4d8b-9667-78082cfe33ac

**Comment by JaGNUar** [comment]
lavender_lineage-20.0_1687934057

**Comment by 0xsharkboy** [comment]
Try to clear cache and storage of the app
