### ISSUE TITLE
[Bug]Problems occurred when connecting to a WLAN using WPA2/WPA3 mixed mode

### ISSUE THREAD

**Issue by tiehu** [SharkBoy69-CS/Lineage_OTA#3]
Program behavior:
When connecting to a WLAN using WPA2/WPA3 mixed mode, the following bugs occur(I have updated to the latest version):
1. After the system restarts, the WLAN cannot be automatically reconnected, and the system displays that the access point is temporarily full.
2. Even if Use Device MAC is selected during the first connection, the random MAC is still used.
3. The saved WLAN cannot be modified twice unless the network settings are reset.

How to reproduce:
As long as you connect to a WLAN that uses WPA2/WPA3 mixed mode, you can reliably reproduce the problem.

**Comment by 0xsharkboy** [comment]
Hey, can you try the last build and tell me if it fixed ?

**Comment by tiehu** [comment]
No, there is no fix, I am using the latest version 20230717/1689621138
