### ISSUE TITLE
Battery charge status not displayed - question mark

### ISSUE THREAD

**Issue by Poomex** [SharkBoy69-CS/Lineage_OTA#6]
Hi, since installing the newest version of the ROM the battery percentage has stopped displaying correctly. Sometimes it shows a question mark inside the battery icon. Sometimes it shows the percentage but incorrectly.

 I've tried using the battery calibration app from F-Droid but that had no effect. 
 
 Thanks for helping me out :)

**Comment by 0xsharkboy** [comment]
> Hi, since installing the newest version of the ROM the battery percentage has stopped displaying correctly. Sometimes it shows a question mark inside the battery icon. Sometimes it shows the percentage but incorrectly.
> 
>  I've tried using the battery calibration app from F-Droid but that had no effect. 
>  
>  Thanks for helping me out :)

Hey, yeah the kernel is not reporting the right battery capacity, I changed kernel for the next update
