### ISSUE TITLE
Camera Broken -- After last update

### ISSUE THREAD

**Issue by MequeLovin** [SharkBoy69-CS/Lineage_OTA#9]
Since the last update, I'm not able to use front or back câmera in-apps (ex whatsapp, instagram), it just displays a black screen. 

If I open the camera App, I'm able to use the back camera, but if I switch to the front camera, I'm faces with an error message: "Error configuring Session".

**Comment by 0xsharkboy** [comment]
It has been fixed in the latest build. Thanks for the report
